FROM registry.k8s.io/kubectl:v1.35.0 AS kubectl

FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV HOME=/tmp

WORKDIR /app

RUN pip install --no-cache-dir kubernetes==35.0.0
COPY --from=kubectl /bin/kubectl /usr/local/bin/kubectl

COPY sandbox_inspector /app/sandbox_inspector

CMD ["sleep","infinity"]
