[project]
name = "demo04"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepagents>=0.5.3",
    "dotenv>=0.9.9",
    "kubernetes>=35.0.0",
    "langchain-community>=0.4.1",
    "langchain-litellm>=0.6.4",
    "langchain-openai>=1.1.15",
    "langgraph>=1.1.8",
    "tavily-python>=0.7.23",
]
