apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - victorialogs-statefulset.yaml
  - fluent-bit-rbac.yaml
  - fluent-bit-configmap.yaml
  - fluent-bit-daemonset.yaml
  - event-exporter-rbac.yaml
  - event-exporter-configmap.yaml
  - event-exporter-deployment.yaml
